<?php

namespace Tests\Unit;

use App\Recipient;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class RecipientTest extends TestCase
{
    use DatabaseTransactions;
    protected $recipient;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->recipient = factory(Recipient::class)->create();

    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testIfWeCanCreateReciepient()
    {
        $response = $this->post('/recipients', ['name'=>$this->recipient->name, 'email' => $this->recipient->email]);

        // Redirects after creating the Special Offer
        $response->assertStatus(302);
//        $response->assertRedirectedTo(route('recipients.index'));
    }
}
